version: '3.8'

services:
  cf-workers-sub:
    build: .
    container_name: cf-workers-sub
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      # 从 .env 文件读取环境变量
      - TOKEN=${TOKEN:-auto}
      - GUESTTOKEN=${GUESTTOKEN:-}
      - FILENAME=${FILENAME:-CF-Workers-SUB}
      - SUBUPTIME=${SUBUPTIME:-6}
      - TGTOKEN=${TGTOKEN:-}
      - TGID=${TGID:-}
      - TG=${TG:-0}
      - SUBAPI=${SUBAPI:-https://sub.nasl.cc:8888}
      - SUBCONFIG=${SUBCONFIG:-https://raw.githubusercontent.com/Frankieli123/clash2/refs/heads/main/Clash-LIAN.ini}
      - LINK=${LINK:-}
      - LINKSUB=${LINKSUB:-}
      - URL302=${URL302:-}
      - URL=${URL:-}
      - WARP=${WARP:-}
      - KV=${KV:-true}
      - DATA_DIR=${DATA_DIR:-./data}
      - EXTERNAL_URL=${EXTERNAL_URL:-}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cf-workers-sub-network

  # 可选：Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: cf-workers-sub-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - cf-workers-sub
    networks:
      - cf-workers-sub-network
    profiles:
      - nginx

networks:
  cf-workers-sub-network:
    driver: bridge

volumes:
  data:
  logs:
