version: '3.8'

services:
  app:
    build: .
    container_name: cf-workers-sub
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      # 基础配置
      - TOKEN=${TOKEN:-auto}
      - GUESTTOKEN=${GUESTTOKEN:-}
      - FILENAME=${FILENAME:-CF-Workers-SUB}
      - SUBUPTIME=${SUBUPTIME:-6}
      # Telegram通知
      - TGTOKEN=${TGTOKEN:-}
      - TGID=${TGID:-}
      - TG=${TG:-0}
      # 订阅转换配置
      - SUBAPI=${SUBAPI:-https://sub.nasl.cc:8888}
      - SUBCONFIG=${SUBCONFIG:-https://raw.githubusercontent.com/Frankieli123/clash2/refs/heads/main/Clash-LIAN.ini}
      # 订阅源配置
      - LINK=${LINK:-}
      - LINKSUB=${LINKSUB:-}
      # 其他配置
      - URL302=${URL302:-}
      - URL=${URL:-}
      - WARP=${WARP:-}
      - KV=${KV:-true}
      # 存储配置 - 使用Redis
      - REDIS_URL=redis://redis:6379
      - REDIS_PREFIX=${REDIS_PREFIX:-cf-workers-sub:}
      # 外部访问地址（Coolify会自动设置）
      - EXTERNAL_URL=${EXTERNAL_URL:-}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - cf-workers-sub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: cf-workers-sub-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - cf-workers-sub-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  cf-workers-sub-network:
    driver: bridge

volumes:
  redis-data:
